"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommunicationMessage = void 0;
var typeorm_1 = require("typeorm");
var CommunicationMessage = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('communication_messages')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _tenantId_decorators;
    var _tenantId_initializers = [];
    var _tenantId_extraInitializers = [];
    var _patientId_decorators;
    var _patientId_initializers = [];
    var _patientId_extraInitializers = [];
    var _patientName_decorators;
    var _patientName_initializers = [];
    var _patientName_extraInitializers = [];
    var _recipientPhone_decorators;
    var _recipientPhone_initializers = [];
    var _recipientPhone_extraInitializers = [];
    var _channel_decorators;
    var _channel_initializers = [];
    var _channel_extraInitializers = [];
    var _fallbackChannel_decorators;
    var _fallbackChannel_initializers = [];
    var _fallbackChannel_extraInitializers = [];
    var _priority_decorators;
    var _priority_initializers = [];
    var _priority_extraInitializers = [];
    var _category_decorators;
    var _category_initializers = [];
    var _category_extraInitializers = [];
    var _templateKey_decorators;
    var _templateKey_initializers = [];
    var _templateKey_extraInitializers = [];
    var _messageBody_decorators;
    var _messageBody_initializers = [];
    var _messageBody_extraInitializers = [];
    var _mediaUrl_decorators;
    var _mediaUrl_initializers = [];
    var _mediaUrl_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _provider_decorators;
    var _provider_initializers = [];
    var _provider_extraInitializers = [];
    var _providerMessageId_decorators;
    var _providerMessageId_initializers = [];
    var _providerMessageId_extraInitializers = [];
    var _retryCount_decorators;
    var _retryCount_initializers = [];
    var _retryCount_extraInitializers = [];
    var _maxRetries_decorators;
    var _maxRetries_initializers = [];
    var _maxRetries_extraInitializers = [];
    var _errorMessage_decorators;
    var _errorMessage_initializers = [];
    var _errorMessage_extraInitializers = [];
    var _sentAt_decorators;
    var _sentAt_initializers = [];
    var _sentAt_extraInitializers = [];
    var _deliveredAt_decorators;
    var _deliveredAt_initializers = [];
    var _deliveredAt_extraInitializers = [];
    var _readAt_decorators;
    var _readAt_initializers = [];
    var _readAt_extraInitializers = [];
    var _costEstimate_decorators;
    var _costEstimate_initializers = [];
    var _costEstimate_extraInitializers = [];
    var _currency_decorators;
    var _currency_initializers = [];
    var _currency_extraInitializers = [];
    var _smsSegments_decorators;
    var _smsSegments_initializers = [];
    var _smsSegments_extraInitializers = [];
    var _patientResponse_decorators;
    var _patientResponse_initializers = [];
    var _patientResponse_extraInitializers = [];
    var _metadata_decorators;
    var _metadata_initializers = [];
    var _metadata_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var CommunicationMessage = _classThis = /** @class */ (function () {
        function CommunicationMessage_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.tenantId = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _tenantId_initializers, void 0));
            this.patientId = (__runInitializers(this, _tenantId_extraInitializers), __runInitializers(this, _patientId_initializers, void 0));
            this.patientName = (__runInitializers(this, _patientId_extraInitializers), __runInitializers(this, _patientName_initializers, void 0));
            this.recipientPhone = (__runInitializers(this, _patientName_extraInitializers), __runInitializers(this, _recipientPhone_initializers, void 0));
            this.channel = (__runInitializers(this, _recipientPhone_extraInitializers), __runInitializers(this, _channel_initializers, void 0)); // 'sms' | 'whatsapp' | 'email'
            this.fallbackChannel = (__runInitializers(this, _channel_extraInitializers), __runInitializers(this, _fallbackChannel_initializers, void 0));
            this.priority = (__runInitializers(this, _fallbackChannel_extraInitializers), __runInitializers(this, _priority_initializers, void 0)); // 'EMERGENCY_STAT' | 'HIGH' | 'NORMAL'
            this.category = (__runInitializers(this, _priority_extraInitializers), __runInitializers(this, _category_initializers, void 0));
            this.templateKey = (__runInitializers(this, _category_extraInitializers), __runInitializers(this, _templateKey_initializers, void 0));
            this.messageBody = (__runInitializers(this, _templateKey_extraInitializers), __runInitializers(this, _messageBody_initializers, void 0));
            this.mediaUrl = (__runInitializers(this, _messageBody_extraInitializers), __runInitializers(this, _mediaUrl_initializers, void 0));
            this.status = (__runInitializers(this, _mediaUrl_extraInitializers), __runInitializers(this, _status_initializers, void 0)); // 'QUEUED' | 'SENT' | 'DELIVERED' | 'READ' | 'FAILED' | 'OPTED_OUT'
            this.provider = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _provider_initializers, void 0)); // 'AfricasTalking' | 'Twilio' | 'WhatsAppCloud' | 'LocalGsmGateway'
            this.providerMessageId = (__runInitializers(this, _provider_extraInitializers), __runInitializers(this, _providerMessageId_initializers, void 0));
            this.retryCount = (__runInitializers(this, _providerMessageId_extraInitializers), __runInitializers(this, _retryCount_initializers, void 0));
            this.maxRetries = (__runInitializers(this, _retryCount_extraInitializers), __runInitializers(this, _maxRetries_initializers, void 0));
            this.errorMessage = (__runInitializers(this, _maxRetries_extraInitializers), __runInitializers(this, _errorMessage_initializers, void 0));
            this.sentAt = (__runInitializers(this, _errorMessage_extraInitializers), __runInitializers(this, _sentAt_initializers, void 0));
            this.deliveredAt = (__runInitializers(this, _sentAt_extraInitializers), __runInitializers(this, _deliveredAt_initializers, void 0));
            this.readAt = (__runInitializers(this, _deliveredAt_extraInitializers), __runInitializers(this, _readAt_initializers, void 0));
            this.costEstimate = (__runInitializers(this, _readAt_extraInitializers), __runInitializers(this, _costEstimate_initializers, void 0));
            this.currency = (__runInitializers(this, _costEstimate_extraInitializers), __runInitializers(this, _currency_initializers, void 0));
            this.smsSegments = (__runInitializers(this, _currency_extraInitializers), __runInitializers(this, _smsSegments_initializers, void 0));
            this.patientResponse = (__runInitializers(this, _smsSegments_extraInitializers), __runInitializers(this, _patientResponse_initializers, void 0));
            this.metadata = (__runInitializers(this, _patientResponse_extraInitializers), __runInitializers(this, _metadata_initializers, void 0));
            this.createdAt = (__runInitializers(this, _metadata_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
        return CommunicationMessage_1;
    }());
    __setFunctionName(_classThis, "CommunicationMessage");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _tenantId_decorators = [(0, typeorm_1.Index)(), (0, typeorm_1.Column)({ name: 'tenant_id', default: 'tenant_default' })];
        _patientId_decorators = [(0, typeorm_1.Index)(), (0, typeorm_1.Column)({ name: 'patient_id', nullable: true })];
        _patientName_decorators = [(0, typeorm_1.Column)({ name: 'patient_name', nullable: true })];
        _recipientPhone_decorators = [(0, typeorm_1.Index)(), (0, typeorm_1.Column)({ name: 'recipient_phone' })];
        _channel_decorators = [(0, typeorm_1.Column)({ default: 'sms' })];
        _fallbackChannel_decorators = [(0, typeorm_1.Column)({ name: 'fallback_channel', nullable: true })];
        _priority_decorators = [(0, typeorm_1.Column)({ default: 'NORMAL' })];
        _category_decorators = [(0, typeorm_1.Index)(), (0, typeorm_1.Column)({ default: 'GENERAL_BROADCAST' })];
        _templateKey_decorators = [(0, typeorm_1.Column)({ name: 'template_key', nullable: true })];
        _messageBody_decorators = [(0, typeorm_1.Column)({ name: 'message_body', type: 'text' })];
        _mediaUrl_decorators = [(0, typeorm_1.Column)({ name: 'media_url', type: 'text', nullable: true })];
        _status_decorators = [(0, typeorm_1.Index)(), (0, typeorm_1.Column)({ default: 'QUEUED' })];
        _provider_decorators = [(0, typeorm_1.Column)({ default: 'AfricasTalking' })];
        _providerMessageId_decorators = [(0, typeorm_1.Column)({ name: 'provider_message_id', nullable: true })];
        _retryCount_decorators = [(0, typeorm_1.Column)({ name: 'retry_count', type: 'int', default: 0 })];
        _maxRetries_decorators = [(0, typeorm_1.Column)({ name: 'max_retries', type: 'int', default: 3 })];
        _errorMessage_decorators = [(0, typeorm_1.Column)({ name: 'error_message', type: 'text', nullable: true })];
        _sentAt_decorators = [(0, typeorm_1.Column)({ name: 'sent_at', type: 'timestamp', nullable: true })];
        _deliveredAt_decorators = [(0, typeorm_1.Column)({ name: 'delivered_at', type: 'timestamp', nullable: true })];
        _readAt_decorators = [(0, typeorm_1.Column)({ name: 'read_at', type: 'timestamp', nullable: true })];
        _costEstimate_decorators = [(0, typeorm_1.Column)({ name: 'cost_estimate', type: 'decimal', precision: 10, scale: 4, default: 0.0 })];
        _currency_decorators = [(0, typeorm_1.Column)({ default: 'KES' })];
        _smsSegments_decorators = [(0, typeorm_1.Column)({ name: 'sms_segments', type: 'int', default: 1 })];
        _patientResponse_decorators = [(0, typeorm_1.Column)({ name: 'patient_response', type: 'json', nullable: true })];
        _metadata_decorators = [(0, typeorm_1.Column)({ type: 'json', nullable: true })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)({ name: 'created_at' })];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _tenantId_decorators, { kind: "field", name: "tenantId", static: false, private: false, access: { has: function (obj) { return "tenantId" in obj; }, get: function (obj) { return obj.tenantId; }, set: function (obj, value) { obj.tenantId = value; } }, metadata: _metadata }, _tenantId_initializers, _tenantId_extraInitializers);
        __esDecorate(null, null, _patientId_decorators, { kind: "field", name: "patientId", static: false, private: false, access: { has: function (obj) { return "patientId" in obj; }, get: function (obj) { return obj.patientId; }, set: function (obj, value) { obj.patientId = value; } }, metadata: _metadata }, _patientId_initializers, _patientId_extraInitializers);
        __esDecorate(null, null, _patientName_decorators, { kind: "field", name: "patientName", static: false, private: false, access: { has: function (obj) { return "patientName" in obj; }, get: function (obj) { return obj.patientName; }, set: function (obj, value) { obj.patientName = value; } }, metadata: _metadata }, _patientName_initializers, _patientName_extraInitializers);
        __esDecorate(null, null, _recipientPhone_decorators, { kind: "field", name: "recipientPhone", static: false, private: false, access: { has: function (obj) { return "recipientPhone" in obj; }, get: function (obj) { return obj.recipientPhone; }, set: function (obj, value) { obj.recipientPhone = value; } }, metadata: _metadata }, _recipientPhone_initializers, _recipientPhone_extraInitializers);
        __esDecorate(null, null, _channel_decorators, { kind: "field", name: "channel", static: false, private: false, access: { has: function (obj) { return "channel" in obj; }, get: function (obj) { return obj.channel; }, set: function (obj, value) { obj.channel = value; } }, metadata: _metadata }, _channel_initializers, _channel_extraInitializers);
        __esDecorate(null, null, _fallbackChannel_decorators, { kind: "field", name: "fallbackChannel", static: false, private: false, access: { has: function (obj) { return "fallbackChannel" in obj; }, get: function (obj) { return obj.fallbackChannel; }, set: function (obj, value) { obj.fallbackChannel = value; } }, metadata: _metadata }, _fallbackChannel_initializers, _fallbackChannel_extraInitializers);
        __esDecorate(null, null, _priority_decorators, { kind: "field", name: "priority", static: false, private: false, access: { has: function (obj) { return "priority" in obj; }, get: function (obj) { return obj.priority; }, set: function (obj, value) { obj.priority = value; } }, metadata: _metadata }, _priority_initializers, _priority_extraInitializers);
        __esDecorate(null, null, _category_decorators, { kind: "field", name: "category", static: false, private: false, access: { has: function (obj) { return "category" in obj; }, get: function (obj) { return obj.category; }, set: function (obj, value) { obj.category = value; } }, metadata: _metadata }, _category_initializers, _category_extraInitializers);
        __esDecorate(null, null, _templateKey_decorators, { kind: "field", name: "templateKey", static: false, private: false, access: { has: function (obj) { return "templateKey" in obj; }, get: function (obj) { return obj.templateKey; }, set: function (obj, value) { obj.templateKey = value; } }, metadata: _metadata }, _templateKey_initializers, _templateKey_extraInitializers);
        __esDecorate(null, null, _messageBody_decorators, { kind: "field", name: "messageBody", static: false, private: false, access: { has: function (obj) { return "messageBody" in obj; }, get: function (obj) { return obj.messageBody; }, set: function (obj, value) { obj.messageBody = value; } }, metadata: _metadata }, _messageBody_initializers, _messageBody_extraInitializers);
        __esDecorate(null, null, _mediaUrl_decorators, { kind: "field", name: "mediaUrl", static: false, private: false, access: { has: function (obj) { return "mediaUrl" in obj; }, get: function (obj) { return obj.mediaUrl; }, set: function (obj, value) { obj.mediaUrl = value; } }, metadata: _metadata }, _mediaUrl_initializers, _mediaUrl_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _provider_decorators, { kind: "field", name: "provider", static: false, private: false, access: { has: function (obj) { return "provider" in obj; }, get: function (obj) { return obj.provider; }, set: function (obj, value) { obj.provider = value; } }, metadata: _metadata }, _provider_initializers, _provider_extraInitializers);
        __esDecorate(null, null, _providerMessageId_decorators, { kind: "field", name: "providerMessageId", static: false, private: false, access: { has: function (obj) { return "providerMessageId" in obj; }, get: function (obj) { return obj.providerMessageId; }, set: function (obj, value) { obj.providerMessageId = value; } }, metadata: _metadata }, _providerMessageId_initializers, _providerMessageId_extraInitializers);
        __esDecorate(null, null, _retryCount_decorators, { kind: "field", name: "retryCount", static: false, private: false, access: { has: function (obj) { return "retryCount" in obj; }, get: function (obj) { return obj.retryCount; }, set: function (obj, value) { obj.retryCount = value; } }, metadata: _metadata }, _retryCount_initializers, _retryCount_extraInitializers);
        __esDecorate(null, null, _maxRetries_decorators, { kind: "field", name: "maxRetries", static: false, private: false, access: { has: function (obj) { return "maxRetries" in obj; }, get: function (obj) { return obj.maxRetries; }, set: function (obj, value) { obj.maxRetries = value; } }, metadata: _metadata }, _maxRetries_initializers, _maxRetries_extraInitializers);
        __esDecorate(null, null, _errorMessage_decorators, { kind: "field", name: "errorMessage", static: false, private: false, access: { has: function (obj) { return "errorMessage" in obj; }, get: function (obj) { return obj.errorMessage; }, set: function (obj, value) { obj.errorMessage = value; } }, metadata: _metadata }, _errorMessage_initializers, _errorMessage_extraInitializers);
        __esDecorate(null, null, _sentAt_decorators, { kind: "field", name: "sentAt", static: false, private: false, access: { has: function (obj) { return "sentAt" in obj; }, get: function (obj) { return obj.sentAt; }, set: function (obj, value) { obj.sentAt = value; } }, metadata: _metadata }, _sentAt_initializers, _sentAt_extraInitializers);
        __esDecorate(null, null, _deliveredAt_decorators, { kind: "field", name: "deliveredAt", static: false, private: false, access: { has: function (obj) { return "deliveredAt" in obj; }, get: function (obj) { return obj.deliveredAt; }, set: function (obj, value) { obj.deliveredAt = value; } }, metadata: _metadata }, _deliveredAt_initializers, _deliveredAt_extraInitializers);
        __esDecorate(null, null, _readAt_decorators, { kind: "field", name: "readAt", static: false, private: false, access: { has: function (obj) { return "readAt" in obj; }, get: function (obj) { return obj.readAt; }, set: function (obj, value) { obj.readAt = value; } }, metadata: _metadata }, _readAt_initializers, _readAt_extraInitializers);
        __esDecorate(null, null, _costEstimate_decorators, { kind: "field", name: "costEstimate", static: false, private: false, access: { has: function (obj) { return "costEstimate" in obj; }, get: function (obj) { return obj.costEstimate; }, set: function (obj, value) { obj.costEstimate = value; } }, metadata: _metadata }, _costEstimate_initializers, _costEstimate_extraInitializers);
        __esDecorate(null, null, _currency_decorators, { kind: "field", name: "currency", static: false, private: false, access: { has: function (obj) { return "currency" in obj; }, get: function (obj) { return obj.currency; }, set: function (obj, value) { obj.currency = value; } }, metadata: _metadata }, _currency_initializers, _currency_extraInitializers);
        __esDecorate(null, null, _smsSegments_decorators, { kind: "field", name: "smsSegments", static: false, private: false, access: { has: function (obj) { return "smsSegments" in obj; }, get: function (obj) { return obj.smsSegments; }, set: function (obj, value) { obj.smsSegments = value; } }, metadata: _metadata }, _smsSegments_initializers, _smsSegments_extraInitializers);
        __esDecorate(null, null, _patientResponse_decorators, { kind: "field", name: "patientResponse", static: false, private: false, access: { has: function (obj) { return "patientResponse" in obj; }, get: function (obj) { return obj.patientResponse; }, set: function (obj, value) { obj.patientResponse = value; } }, metadata: _metadata }, _patientResponse_initializers, _patientResponse_extraInitializers);
        __esDecorate(null, null, _metadata_decorators, { kind: "field", name: "metadata", static: false, private: false, access: { has: function (obj) { return "metadata" in obj; }, get: function (obj) { return obj.metadata; }, set: function (obj, value) { obj.metadata = value; } }, metadata: _metadata }, _metadata_initializers, _metadata_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        CommunicationMessage = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return CommunicationMessage = _classThis;
}();
exports.CommunicationMessage = CommunicationMessage;
