"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.PacsStudyEntity = void 0;
var typeorm_1 = require("typeorm");
var PacsStudyEntity = function () {
    var _classDecorators = [(0, typeorm_1.Entity)('pacs_studies')];
    var _classDescriptor;
    var _classExtraInitializers = [];
    var _classThis;
    var _id_decorators;
    var _id_initializers = [];
    var _id_extraInitializers = [];
    var _studyInstanceUid_decorators;
    var _studyInstanceUid_initializers = [];
    var _studyInstanceUid_extraInitializers = [];
    var _accessionNumber_decorators;
    var _accessionNumber_initializers = [];
    var _accessionNumber_extraInitializers = [];
    var _patientId_decorators;
    var _patientId_initializers = [];
    var _patientId_extraInitializers = [];
    var _patientMRN_decorators;
    var _patientMRN_initializers = [];
    var _patientMRN_extraInitializers = [];
    var _patientName_decorators;
    var _patientName_initializers = [];
    var _patientName_extraInitializers = [];
    var _patientBirthDate_decorators;
    var _patientBirthDate_initializers = [];
    var _patientBirthDate_extraInitializers = [];
    var _patientSex_decorators;
    var _patientSex_initializers = [];
    var _patientSex_extraInitializers = [];
    var _studyDate_decorators;
    var _studyDate_initializers = [];
    var _studyDate_extraInitializers = [];
    var _studyTime_decorators;
    var _studyTime_initializers = [];
    var _studyTime_extraInitializers = [];
    var _studyDescription_decorators;
    var _studyDescription_initializers = [];
    var _studyDescription_extraInitializers = [];
    var _modality_decorators;
    var _modality_initializers = [];
    var _modality_extraInitializers = [];
    var _modalitiesInStudy_decorators;
    var _modalitiesInStudy_initializers = [];
    var _modalitiesInStudy_extraInitializers = [];
    var _seriesCount_decorators;
    var _seriesCount_initializers = [];
    var _seriesCount_extraInitializers = [];
    var _instanceCount_decorators;
    var _instanceCount_initializers = [];
    var _instanceCount_extraInitializers = [];
    var _institutionName_decorators;
    var _institutionName_initializers = [];
    var _institutionName_extraInitializers = [];
    var _pacsServerId_decorators;
    var _pacsServerId_initializers = [];
    var _pacsServerId_extraInitializers = [];
    var _pacsServerName_decorators;
    var _pacsServerName_initializers = [];
    var _pacsServerName_extraInitializers = [];
    var _previewThumbnailUrl_decorators;
    var _previewThumbnailUrl_initializers = [];
    var _previewThumbnailUrl_extraInitializers = [];
    var _storagePath_decorators;
    var _storagePath_initializers = [];
    var _storagePath_extraInitializers = [];
    var _status_decorators;
    var _status_initializers = [];
    var _status_extraInitializers = [];
    var _seriesJson_decorators;
    var _seriesJson_initializers = [];
    var _seriesJson_extraInitializers = [];
    var _tenantId_decorators;
    var _tenantId_initializers = [];
    var _tenantId_extraInitializers = [];
    var _createdAt_decorators;
    var _createdAt_initializers = [];
    var _createdAt_extraInitializers = [];
    var _updatedAt_decorators;
    var _updatedAt_initializers = [];
    var _updatedAt_extraInitializers = [];
    var PacsStudyEntity = _classThis = /** @class */ (function () {
        function PacsStudyEntity_1() {
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.studyInstanceUid = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _studyInstanceUid_initializers, void 0));
            this.accessionNumber = (__runInitializers(this, _studyInstanceUid_extraInitializers), __runInitializers(this, _accessionNumber_initializers, void 0));
            this.patientId = (__runInitializers(this, _accessionNumber_extraInitializers), __runInitializers(this, _patientId_initializers, void 0));
            this.patientMRN = (__runInitializers(this, _patientId_extraInitializers), __runInitializers(this, _patientMRN_initializers, void 0));
            this.patientName = (__runInitializers(this, _patientMRN_extraInitializers), __runInitializers(this, _patientName_initializers, void 0));
            this.patientBirthDate = (__runInitializers(this, _patientName_extraInitializers), __runInitializers(this, _patientBirthDate_initializers, void 0));
            this.patientSex = (__runInitializers(this, _patientBirthDate_extraInitializers), __runInitializers(this, _patientSex_initializers, void 0));
            this.studyDate = (__runInitializers(this, _patientSex_extraInitializers), __runInitializers(this, _studyDate_initializers, void 0));
            this.studyTime = (__runInitializers(this, _studyDate_extraInitializers), __runInitializers(this, _studyTime_initializers, void 0));
            this.studyDescription = (__runInitializers(this, _studyTime_extraInitializers), __runInitializers(this, _studyDescription_initializers, void 0));
            this.modality = (__runInitializers(this, _studyDescription_extraInitializers), __runInitializers(this, _modality_initializers, void 0));
            this.modalitiesInStudy = (__runInitializers(this, _modality_extraInitializers), __runInitializers(this, _modalitiesInStudy_initializers, void 0));
            this.seriesCount = (__runInitializers(this, _modalitiesInStudy_extraInitializers), __runInitializers(this, _seriesCount_initializers, void 0));
            this.instanceCount = (__runInitializers(this, _seriesCount_extraInitializers), __runInitializers(this, _instanceCount_initializers, void 0));
            this.institutionName = (__runInitializers(this, _instanceCount_extraInitializers), __runInitializers(this, _institutionName_initializers, void 0));
            this.pacsServerId = (__runInitializers(this, _institutionName_extraInitializers), __runInitializers(this, _pacsServerId_initializers, void 0));
            this.pacsServerName = (__runInitializers(this, _pacsServerId_extraInitializers), __runInitializers(this, _pacsServerName_initializers, void 0));
            this.previewThumbnailUrl = (__runInitializers(this, _pacsServerName_extraInitializers), __runInitializers(this, _previewThumbnailUrl_initializers, void 0));
            this.storagePath = (__runInitializers(this, _previewThumbnailUrl_extraInitializers), __runInitializers(this, _storagePath_initializers, void 0));
            this.status = (__runInitializers(this, _storagePath_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.seriesJson = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _seriesJson_initializers, void 0));
            this.tenantId = (__runInitializers(this, _seriesJson_extraInitializers), __runInitializers(this, _tenantId_initializers, void 0));
            this.createdAt = (__runInitializers(this, _tenantId_extraInitializers), __runInitializers(this, _createdAt_initializers, void 0));
            this.updatedAt = (__runInitializers(this, _createdAt_extraInitializers), __runInitializers(this, _updatedAt_initializers, void 0));
            __runInitializers(this, _updatedAt_extraInitializers);
        }
        return PacsStudyEntity_1;
    }());
    __setFunctionName(_classThis, "PacsStudyEntity");
    (function () {
        var _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(null) : void 0;
        _id_decorators = [(0, typeorm_1.PrimaryGeneratedColumn)('uuid')];
        _studyInstanceUid_decorators = [(0, typeorm_1.Column)({ name: 'study_instance_uid', unique: true })];
        _accessionNumber_decorators = [(0, typeorm_1.Column)({ name: 'accession_number', nullable: true })];
        _patientId_decorators = [(0, typeorm_1.Column)({ name: 'patient_id', nullable: true })];
        _patientMRN_decorators = [(0, typeorm_1.Column)({ name: 'patient_mrn' })];
        _patientName_decorators = [(0, typeorm_1.Column)({ name: 'patient_name' })];
        _patientBirthDate_decorators = [(0, typeorm_1.Column)({ name: 'patient_birth_date', nullable: true })];
        _patientSex_decorators = [(0, typeorm_1.Column)({ name: 'patient_sex', nullable: true })];
        _studyDate_decorators = [(0, typeorm_1.Column)({ name: 'study_date' })];
        _studyTime_decorators = [(0, typeorm_1.Column)({ name: 'study_time', nullable: true })];
        _studyDescription_decorators = [(0, typeorm_1.Column)({ name: 'study_description' })];
        _modality_decorators = [(0, typeorm_1.Column)({ name: 'modality' })];
        _modalitiesInStudy_decorators = [(0, typeorm_1.Column)({ name: 'modalities_in_study', type: 'simple-json', nullable: true })];
        _seriesCount_decorators = [(0, typeorm_1.Column)({ name: 'series_count', default: 1 })];
        _instanceCount_decorators = [(0, typeorm_1.Column)({ name: 'instance_count', default: 1 })];
        _institutionName_decorators = [(0, typeorm_1.Column)({ name: 'institution_name', nullable: true })];
        _pacsServerId_decorators = [(0, typeorm_1.Column)({ name: 'pacs_server_id', nullable: true })];
        _pacsServerName_decorators = [(0, typeorm_1.Column)({ name: 'pacs_server_name', nullable: true })];
        _previewThumbnailUrl_decorators = [(0, typeorm_1.Column)({ name: 'preview_thumbnail_url', type: 'text', nullable: true })];
        _storagePath_decorators = [(0, typeorm_1.Column)({ name: 'storage_path', type: 'text', nullable: true })];
        _status_decorators = [(0, typeorm_1.Column)({ name: 'status', default: 'ONLINE' })];
        _seriesJson_decorators = [(0, typeorm_1.Column)({ name: 'series_json', type: 'simple-json', nullable: true })];
        _tenantId_decorators = [(0, typeorm_1.Column)({ name: 'tenant_id', default: 'tenant_001' })];
        _createdAt_decorators = [(0, typeorm_1.CreateDateColumn)({ name: 'created_at' })];
        _updatedAt_decorators = [(0, typeorm_1.UpdateDateColumn)({ name: 'updated_at' })];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: function (obj) { return "id" in obj; }, get: function (obj) { return obj.id; }, set: function (obj, value) { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _studyInstanceUid_decorators, { kind: "field", name: "studyInstanceUid", static: false, private: false, access: { has: function (obj) { return "studyInstanceUid" in obj; }, get: function (obj) { return obj.studyInstanceUid; }, set: function (obj, value) { obj.studyInstanceUid = value; } }, metadata: _metadata }, _studyInstanceUid_initializers, _studyInstanceUid_extraInitializers);
        __esDecorate(null, null, _accessionNumber_decorators, { kind: "field", name: "accessionNumber", static: false, private: false, access: { has: function (obj) { return "accessionNumber" in obj; }, get: function (obj) { return obj.accessionNumber; }, set: function (obj, value) { obj.accessionNumber = value; } }, metadata: _metadata }, _accessionNumber_initializers, _accessionNumber_extraInitializers);
        __esDecorate(null, null, _patientId_decorators, { kind: "field", name: "patientId", static: false, private: false, access: { has: function (obj) { return "patientId" in obj; }, get: function (obj) { return obj.patientId; }, set: function (obj, value) { obj.patientId = value; } }, metadata: _metadata }, _patientId_initializers, _patientId_extraInitializers);
        __esDecorate(null, null, _patientMRN_decorators, { kind: "field", name: "patientMRN", static: false, private: false, access: { has: function (obj) { return "patientMRN" in obj; }, get: function (obj) { return obj.patientMRN; }, set: function (obj, value) { obj.patientMRN = value; } }, metadata: _metadata }, _patientMRN_initializers, _patientMRN_extraInitializers);
        __esDecorate(null, null, _patientName_decorators, { kind: "field", name: "patientName", static: false, private: false, access: { has: function (obj) { return "patientName" in obj; }, get: function (obj) { return obj.patientName; }, set: function (obj, value) { obj.patientName = value; } }, metadata: _metadata }, _patientName_initializers, _patientName_extraInitializers);
        __esDecorate(null, null, _patientBirthDate_decorators, { kind: "field", name: "patientBirthDate", static: false, private: false, access: { has: function (obj) { return "patientBirthDate" in obj; }, get: function (obj) { return obj.patientBirthDate; }, set: function (obj, value) { obj.patientBirthDate = value; } }, metadata: _metadata }, _patientBirthDate_initializers, _patientBirthDate_extraInitializers);
        __esDecorate(null, null, _patientSex_decorators, { kind: "field", name: "patientSex", static: false, private: false, access: { has: function (obj) { return "patientSex" in obj; }, get: function (obj) { return obj.patientSex; }, set: function (obj, value) { obj.patientSex = value; } }, metadata: _metadata }, _patientSex_initializers, _patientSex_extraInitializers);
        __esDecorate(null, null, _studyDate_decorators, { kind: "field", name: "studyDate", static: false, private: false, access: { has: function (obj) { return "studyDate" in obj; }, get: function (obj) { return obj.studyDate; }, set: function (obj, value) { obj.studyDate = value; } }, metadata: _metadata }, _studyDate_initializers, _studyDate_extraInitializers);
        __esDecorate(null, null, _studyTime_decorators, { kind: "field", name: "studyTime", static: false, private: false, access: { has: function (obj) { return "studyTime" in obj; }, get: function (obj) { return obj.studyTime; }, set: function (obj, value) { obj.studyTime = value; } }, metadata: _metadata }, _studyTime_initializers, _studyTime_extraInitializers);
        __esDecorate(null, null, _studyDescription_decorators, { kind: "field", name: "studyDescription", static: false, private: false, access: { has: function (obj) { return "studyDescription" in obj; }, get: function (obj) { return obj.studyDescription; }, set: function (obj, value) { obj.studyDescription = value; } }, metadata: _metadata }, _studyDescription_initializers, _studyDescription_extraInitializers);
        __esDecorate(null, null, _modality_decorators, { kind: "field", name: "modality", static: false, private: false, access: { has: function (obj) { return "modality" in obj; }, get: function (obj) { return obj.modality; }, set: function (obj, value) { obj.modality = value; } }, metadata: _metadata }, _modality_initializers, _modality_extraInitializers);
        __esDecorate(null, null, _modalitiesInStudy_decorators, { kind: "field", name: "modalitiesInStudy", static: false, private: false, access: { has: function (obj) { return "modalitiesInStudy" in obj; }, get: function (obj) { return obj.modalitiesInStudy; }, set: function (obj, value) { obj.modalitiesInStudy = value; } }, metadata: _metadata }, _modalitiesInStudy_initializers, _modalitiesInStudy_extraInitializers);
        __esDecorate(null, null, _seriesCount_decorators, { kind: "field", name: "seriesCount", static: false, private: false, access: { has: function (obj) { return "seriesCount" in obj; }, get: function (obj) { return obj.seriesCount; }, set: function (obj, value) { obj.seriesCount = value; } }, metadata: _metadata }, _seriesCount_initializers, _seriesCount_extraInitializers);
        __esDecorate(null, null, _instanceCount_decorators, { kind: "field", name: "instanceCount", static: false, private: false, access: { has: function (obj) { return "instanceCount" in obj; }, get: function (obj) { return obj.instanceCount; }, set: function (obj, value) { obj.instanceCount = value; } }, metadata: _metadata }, _instanceCount_initializers, _instanceCount_extraInitializers);
        __esDecorate(null, null, _institutionName_decorators, { kind: "field", name: "institutionName", static: false, private: false, access: { has: function (obj) { return "institutionName" in obj; }, get: function (obj) { return obj.institutionName; }, set: function (obj, value) { obj.institutionName = value; } }, metadata: _metadata }, _institutionName_initializers, _institutionName_extraInitializers);
        __esDecorate(null, null, _pacsServerId_decorators, { kind: "field", name: "pacsServerId", static: false, private: false, access: { has: function (obj) { return "pacsServerId" in obj; }, get: function (obj) { return obj.pacsServerId; }, set: function (obj, value) { obj.pacsServerId = value; } }, metadata: _metadata }, _pacsServerId_initializers, _pacsServerId_extraInitializers);
        __esDecorate(null, null, _pacsServerName_decorators, { kind: "field", name: "pacsServerName", static: false, private: false, access: { has: function (obj) { return "pacsServerName" in obj; }, get: function (obj) { return obj.pacsServerName; }, set: function (obj, value) { obj.pacsServerName = value; } }, metadata: _metadata }, _pacsServerName_initializers, _pacsServerName_extraInitializers);
        __esDecorate(null, null, _previewThumbnailUrl_decorators, { kind: "field", name: "previewThumbnailUrl", static: false, private: false, access: { has: function (obj) { return "previewThumbnailUrl" in obj; }, get: function (obj) { return obj.previewThumbnailUrl; }, set: function (obj, value) { obj.previewThumbnailUrl = value; } }, metadata: _metadata }, _previewThumbnailUrl_initializers, _previewThumbnailUrl_extraInitializers);
        __esDecorate(null, null, _storagePath_decorators, { kind: "field", name: "storagePath", static: false, private: false, access: { has: function (obj) { return "storagePath" in obj; }, get: function (obj) { return obj.storagePath; }, set: function (obj, value) { obj.storagePath = value; } }, metadata: _metadata }, _storagePath_initializers, _storagePath_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: function (obj) { return "status" in obj; }, get: function (obj) { return obj.status; }, set: function (obj, value) { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _seriesJson_decorators, { kind: "field", name: "seriesJson", static: false, private: false, access: { has: function (obj) { return "seriesJson" in obj; }, get: function (obj) { return obj.seriesJson; }, set: function (obj, value) { obj.seriesJson = value; } }, metadata: _metadata }, _seriesJson_initializers, _seriesJson_extraInitializers);
        __esDecorate(null, null, _tenantId_decorators, { kind: "field", name: "tenantId", static: false, private: false, access: { has: function (obj) { return "tenantId" in obj; }, get: function (obj) { return obj.tenantId; }, set: function (obj, value) { obj.tenantId = value; } }, metadata: _metadata }, _tenantId_initializers, _tenantId_extraInitializers);
        __esDecorate(null, null, _createdAt_decorators, { kind: "field", name: "createdAt", static: false, private: false, access: { has: function (obj) { return "createdAt" in obj; }, get: function (obj) { return obj.createdAt; }, set: function (obj, value) { obj.createdAt = value; } }, metadata: _metadata }, _createdAt_initializers, _createdAt_extraInitializers);
        __esDecorate(null, null, _updatedAt_decorators, { kind: "field", name: "updatedAt", static: false, private: false, access: { has: function (obj) { return "updatedAt" in obj; }, get: function (obj) { return obj.updatedAt; }, set: function (obj, value) { obj.updatedAt = value; } }, metadata: _metadata }, _updatedAt_initializers, _updatedAt_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        PacsStudyEntity = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return PacsStudyEntity = _classThis;
}();
exports.PacsStudyEntity = PacsStudyEntity;
